-- Legacy demo fixtures exported from the Rails seed file; legacy owner accounts are intentionally not imported.
with seed_rows (
  title, address, city, state, zipcode, listing_type, building_type, est_payment,
  price, price_sqft, bedroom, bathroom, sqft, built_in, heating, ac, garage,
  overview, key_words, lat, lng, photo_urls
) as (
  values
  ('236 E 78th St', '236 E 78th St, New York, NY 10075', 'New York', 'NY', '10075', 'Sale', 'Apartment', '$3500/month', 700000, 467, 3, 2, 1500, 1990, TRUE, TRUE, TRUE, 'Spacious 4BR 3BA condo with stunning views of Central Park Stylish, Spacious Alcove Studio just steps from Central Park, Fifth Avenue and Carnegie Hall! You can live in the middle of it all!  Priced for an all cash deal!
    This huge alcove studio (approx. 600sf) has been completely gut renovated and cleverly converted into a Junior 2 bedroom apartment.   The gorgeous full separate kitchen features granite counters and flooring, subway tile backsplash, tons of cabinet space... a kitchen that is beautiful to look at and functional for entertaining. The stunning bathroom has marble walls and floors, and lovely mosaic tiled shower, European style pedestal sink and Kohler fixtures.
    This unique apartment has beautiful solid oak parquet floors, plenty of storage and so much more.

    The pet-friendly, full service building has a full time doorman, Concierge, valet and an on-site garage where residents receive a 25% discount. We are close to most subway lines as well as the cross-town buses. There is a monthly special assessment of $220.07 through 2/28/23, in addition to the maintenanceSpacious 4BR 3BA condo with stunning views of Central Park Stylish, Spacious Alcove Studio just steps from Central Park, Fifth Avenue and Carnegie Hall! You can live in the middle of it all!  Priced for an all cash deal!
    This huge alcove studio (approx. 600sf) has been completely gut renovated and cleverly converted into a Junior 2 bedroom apartment.   The gorgeous full separate kitchen features granite counters and flooring, subway tile backsplash, tons of cabinet space... a kitchen that is beautiful to look at and functional for entertaining. The stunning bathroom has marble walls and floors, and lovely mosaic tiled shower, European style pedestal sink and Kohler fixtures.
    This unique apartment has beautiful solid oak parquet floors, plenty of storage and so much more.

    The pet-friendly, full service building has a full time doorman, Concierge, valet and an on-site garage where residents receive a 25% discount. We are close to most subway lines as well as the cross-town buses. There is a monthly special assessment of $220.07 through 2/28/23, in addition to the maintenance.', 'STUDIO ELEVATOR DOORMAN STORAGE ALCOVE BATHROOM', 40.776157, -73.952102, ARRAY['https://villow-seeds.s3.amazonaws.com/house1.webp', 'https://villow-seeds.s3.amazonaws.com/house2.webp', 'https://villow-seeds.s3.amazonaws.com/house3.webp', 'https://villow-seeds.s3.amazonaws.com/4.webp', 'https://villow-seeds.s3.amazonaws.com/5.webp', 'https://villow-seeds.s3.amazonaws.com/6.webp', 'https://villow-seeds.s3.amazonaws.com/7.webp']::text[]),
('200 Park Ave', '200 Park Ave, New York, NY 10007', 'New York', 'NY', '10007', 'Rent', 'Condo', '$4500/month', 900000, 450, 4, 3, 2000, 2000, TRUE, TRUE, TRUE, 'Spacious 4BR 3BA condo with stunning views of Central Park Stylish, Spacious Alcove Studio just steps from Central Park, Fifth Avenue and Carnegie Hall! You can live in the middle of it all!  Priced for an all cash deal!
    This huge alcove studio (approx. 600sf) has been completely gut renovated and cleverly converted into a Junior 2 bedroom apartment.   The gorgeous full separate kitchen features granite counters and flooring, subway tile backsplash, tons of cabinet space... a kitchen that is beautiful to look at and functional for entertaining. The stunning bathroom has marble walls and floors, and lovely mosaic tiled shower, European style pedestal sink and Kohler fixtures.
    This unique apartment has beautiful solid oak parquet floors, plenty of storage and so much more.
    The pet-friendly, full service building has a full time doorman, Concierge, valet and an on-site garage where residents receive a 25% discount. We are close to most subway lines as well as the cross-town buses. There is a monthly special assessment of $220.07 through 2/28/23, in addition to the maintenance.', 'DOORMAN STORAGE ELEVATOR STUDIO ALCOVE BATHROOM', 40.776157, -73.952102, ARRAY['https://villow-seeds.s3.amazonaws.com/house1.webp', 'https://villow-seeds.s3.amazonaws.com/house2.webp', 'https://villow-seeds.s3.amazonaws.com/house3.webp', 'https://villow-seeds.s3.amazonaws.com/4.webp', 'https://villow-seeds.s3.amazonaws.com/5.webp', 'https://villow-seeds.s3.amazonaws.com/6.webp', 'https://villow-seeds.s3.amazonaws.com/7.webp']::text[]),
('300 Broadway', '300 Broadway, New York, NY 10007', 'New York', 'NY', '10007', 'Sale', 'Co-op', '$2500/month', 500000, 500, 2, 1, 1000, 1980, TRUE, TRUE, FALSE, 'Spacious 4BR 3BA condo with stunning views of Central Park Stylish, Spacious Alcove Studio just steps from Central Park, Fifth Avenue and Carnegie Hall! You can live in the middle of it all!  Priced for an all cash deal!
    This huge alcove studio (approx. 600sf) has been completely gut renovated and cleverly converted into a Junior 2 bedroom apartment.   The gorgeous full separate kitchen features granite counters and flooring, subway tile backsplash, tons of cabinet space... a kitchen that is beautiful to look at and functional for entertaining. The stunning bathroom has marble walls and floors, and lovely mosaic tiled shower, European style pedestal sink and Kohler fixtures.
    This unique apartment has beautiful solid oak parquet floors, plenty of storage and so much more.
    The pet-friendly, full service building has a full time doorman, Concierge, valet and an on-site garage where residents receive a 25% discount. We are close to most subway lines as well as the cross-town buses. There is a monthly special assessment of $220.07 through 2/28/23, in addition to the maintenance.', 'ALCOVE ELEVATOR STORAGE STUDIO BATHROOM DOORMAN', 40.776157, -73.952102, ARRAY['https://villow-seeds.s3.amazonaws.com/house1.webp', 'https://villow-seeds.s3.amazonaws.com/house2.webp', 'https://villow-seeds.s3.amazonaws.com/house3.webp', 'https://villow-seeds.s3.amazonaws.com/4.webp', 'https://villow-seeds.s3.amazonaws.com/5.webp', 'https://villow-seeds.s3.amazonaws.com/6.webp', 'https://villow-seeds.s3.amazonaws.com/7.webp']::text[]),
('400 5th Ave', '400 5th Ave, New York, NY 10016', 'New York', 'NY', '10016', 'Rent', 'Apartment', '$4000/month', 800000, 470, 3, 2, 1700, 1990, TRUE, TRUE, TRUE, 'Spacious 4BR 3BA condo with stunning views of Central Park Stylish, Spacious Alcove Studio just steps from Central Park, Fifth Avenue and Carnegie Hall! You can live in the middle of it all!  Priced for an all cash deal!
    This huge alcove studio (approx. 600sf) has been completely gut renovated and cleverly converted into a Junior 2 bedroom apartment.   The gorgeous full separate kitchen features granite counters and flooring, subway tile backsplash, tons of cabinet space... a kitchen that is beautiful to look at and functional for entertaining. The stunning bathroom has marble walls and floors, and lovely mosaic tiled shower, European style pedestal sink and Kohler fixtures.
    This unique apartment has beautiful solid oak parquet floors, plenty of storage and so much more.
    The pet-friendly, full service building has a full time doorman, Concierge, valet and an on-site garage where residents receive a 25% discount. We are close to most subway lines as well as the cross-town buses. There is a monthly special assessment of $220.07 through 2/28/23, in addition to the maintenance.', 'BATHROOM STORAGE DOORMAN STUDIO ELEVATOR ALCOVE', 40.776157, -73.952102, ARRAY['https://villow-seeds.s3.amazonaws.com/house1.webp', 'https://villow-seeds.s3.amazonaws.com/house2.webp', 'https://villow-seeds.s3.amazonaws.com/house3.webp', 'https://villow-seeds.s3.amazonaws.com/4.webp', 'https://villow-seeds.s3.amazonaws.com/5.webp', 'https://villow-seeds.s3.amazonaws.com/6.webp', 'https://villow-seeds.s3.amazonaws.com/7.webp']::text[]),
('500 6th Ave', '500 6th Ave, New York, NY 10011', 'New York', 'NY', '10011', 'Sale', 'Condo', '$3000/month', 600000, 462, 2, 2, 1300, 2000, TRUE, TRUE, FALSE, 'Spacious 4BR 3BA condo with stunning views of Central Park Stylish, Spacious Alcove Studio just steps from Central Park, Fifth Avenue and Carnegie Hall! You can live in the middle of it all!  Priced for an all cash deal!
    This huge alcove studio (approx. 600sf) has been completely gut renovated and cleverly converted into a Junior 2 bedroom apartment.   The gorgeous full separate kitchen features granite counters and flooring, subway tile backsplash, tons of cabinet space... a kitchen that is beautiful to look at and functional for entertaining. The stunning bathroom has marble walls and floors, and lovely mosaic tiled shower, European style pedestal sink and Kohler fixtures.
    This unique apartment has beautiful solid oak parquet floors, plenty of storage and so much more.
    The pet-friendly, full service building has a full time doorman, Concierge, valet and an on-site garage where residents receive a 25% discount. We are close to most subway lines as well as the cross-town buses. There is a monthly special assessment of $220.07 through 2/28/23, in addition to the maintenance.', 'ELEVATOR STUDIO BATHROOM DOORMAN STORAGE ALCOVE', 40.776157, -73.952102, ARRAY['https://villow-seeds.s3.amazonaws.com/house1.webp', 'https://villow-seeds.s3.amazonaws.com/house2.webp', 'https://villow-seeds.s3.amazonaws.com/house3.webp', 'https://villow-seeds.s3.amazonaws.com/4.webp', 'https://villow-seeds.s3.amazonaws.com/5.webp', 'https://villow-seeds.s3.amazonaws.com/6.webp', 'https://villow-seeds.s3.amazonaws.com/7.webp']::text[]),
('500 E 77th St', '500 E 77th St, New York, NY 10162', 'New York', 'NY', '10162', 'Rent', 'Apartment', '$1750/month', 175000, 292, 1, 1, 600, 1985, TRUE, TRUE, TRUE, 'Beautiful and sunny one-bedroom apartment in the heart of Upper East Side! This lovely apartment features hardwood floors, a large living room, updated kitchen, king-size bedroom, and updated bathroom. The building offers 24-hour doorman, elevator, laundry, and gym. Close to many fine restaurants, shopping, and transportation.', '1BR ELEVATOR DOORMAN GYM HARDWOOD FLOORS LAUNDRY', 40.776157, -73.952102, ARRAY['https://villow-seeds.s3.amazonaws.com/house1.webp', 'https://villow-seeds.s3.amazonaws.com/house2.webp', 'https://villow-seeds.s3.amazonaws.com/house3.webp', 'https://villow-seeds.s3.amazonaws.com/4.webp', 'https://villow-seeds.s3.amazonaws.com/5.webp', 'https://villow-seeds.s3.amazonaws.com/6.webp', 'https://villow-seeds.s3.amazonaws.com/7.webp']::text[]),
('1160 3rd Ave', '1160 3rd Ave, New York, NY 10065', 'New York', 'NY', '10065', 'Sale', 'Condo', '$6250/month', 1250000, 833, 3, 2, 1500, 2007, TRUE, TRUE, TRUE, 'This gorgeous 3-bedroom condo features an open living room and dining room with Brazilian cherry wood floors, a custom kitchen with cherry cabinets, granite countertops and high-end stainless-steel appliances, 3 bedrooms with abundant closet space, and 2 marble bathrooms. Building amenities include a doorman, gym, laundry, and roof deck. Great location close to many restaurants, shops, and transportation.', '3BR CONDO ELEVATOR DOORMAN GYM LAUNDRY ROOF DECK', 40.776157, -73.952102, ARRAY['https://villow-seeds.s3.amazonaws.com/house1.webp', 'https://villow-seeds.s3.amazonaws.com/house2.webp', 'https://villow-seeds.s3.amazonaws.com/house3.webp', 'https://villow-seeds.s3.amazonaws.com/4.webp', 'https://villow-seeds.s3.amazonaws.com/5.webp', 'https://villow-seeds.s3.amazonaws.com/6.webp', 'https://villow-seeds.s3.amazonaws.com/7.webp']::text[]),
('151 E 83rd St', '151 E 83rd St, New York, NY 10028', 'New York', 'NY', '10028', 'Rent', 'Apartment', '$425/month', 4250, 8, 0, 1, 500, 1926, TRUE, TRUE, FALSE, 'Amazing studio apartment in a prime Upper East Side location! This lovely studio features high ceilings, hardwood floors, updated kitchen, and updated bathroom. The building is located in a quiet tree-lined street, and features a live-in superintendent, laundry, and bike storage. Close to many great restaurants, shopping, and transportation.', 'STUDIO HARDWOOD FLOORS UPDATED KITCHEN UPDATED BATHROOM LAUNDRY', 40.776157, -73.952102, ARRAY['https://villow-seeds.s3.amazonaws.com/house1.webp', 'https://villow-seeds.s3.amazonaws.com/house2.webp', 'https://villow-seeds.s3.amazonaws.com/house3.webp', 'https://villow-seeds.s3.amazonaws.com/4.webp', 'https://villow-seeds.s3.amazonaws.com/5.webp', 'https://villow-seeds.s3.amazonaws.com/6.webp', 'https://villow-seeds.s3.amazonaws.com/7.webp']::text[]),
('220 E 71st St', '220 E 71st St, New York, NY 10021', 'New York', 'NY', '10021', 'Rent', 'Apartment', '$350/month', 3500, 5, 1, 1, 700, 1960, TRUE, TRUE, FALSE, 'Beautiful one-bedroom apartment in the heart of the Upper East Side! This spacious apartment features large windows, hardwood floors, and a renovated kitchen. The building is well-maintained and features a doorman and laundry facilities. Conveniently located near transportation, shops, and restaurants.', '1BR HARDWOOD FLOORS RENOVATED KITCHEN DOORMAN LAUNDRY', 40.776157, -73.952102, ARRAY['https://villow-seeds.s3.amazonaws.com/house1.webp', 'https://villow-seeds.s3.amazonaws.com/house2.webp', 'https://villow-seeds.s3.amazonaws.com/house3.webp', 'https://villow-seeds.s3.amazonaws.com/4.webp', 'https://villow-seeds.s3.amazonaws.com/5.webp', 'https://villow-seeds.s3.amazonaws.com/6.webp', 'https://villow-seeds.s3.amazonaws.com/7.webp']::text[]),
('1280 5th Ave', '1280 5th Ave, New York, NY 10029', 'New York', 'NY', '10029', 'Sale', 'Condo', '$13,547/month', 6500000, 2600, 3, 3.5, 2500, 2018, TRUE, TRUE, TRUE, 'Luxury three-bedroom condo with stunning views of Central Park! This beautiful apartment features high ceilings, floor-to-ceiling windows, and a gourmet kitchen. The building offers 24-hour doorman service, a fitness center, and a landscaped roof terrace. Located just steps from Central Park and the Museum Mile.', '3BR CONDO CENTRAL PARK VIEWS DOORMAN FITNESS TERRACE', 40.776157, -73.952102, ARRAY['https://villow-seeds.s3.amazonaws.com/house1.webp', 'https://villow-seeds.s3.amazonaws.com/house2.webp', 'https://villow-seeds.s3.amazonaws.com/house3.webp', 'https://villow-seeds.s3.amazonaws.com/4.webp', 'https://villow-seeds.s3.amazonaws.com/5.webp', 'https://villow-seeds.s3.amazonaws.com/6.webp', 'https://villow-seeds.s3.amazonaws.com/7.webp']::text[]),
('114 E 72nd St', '114 E 72nd St, New York, NY 10021', 'New York', 'NY', '10021', 'Sale', 'Co-op', '$3,949/month', 1900000, 1462, 2, 2, 1300, 1948, TRUE, TRUE, FALSE, 'Stylish two-bedroom co-op in a prime Upper East Side location! This renovated apartment features an open layout, high ceilings, and custom built-ins. The building offers a 24-hour doorman, live-in superintendent, and a common roof deck. Close to transportation, shopping, and dining.', '2BR RENOVATED CO-OP DOORMAN ROOF DECK CUSTOM BUILT-INS', 40.776157, -73.952102, ARRAY['https://villow-seeds.s3.amazonaws.com/house1.webp', 'https://villow-seeds.s3.amazonaws.com/house2.webp', 'https://villow-seeds.s3.amazonaws.com/house3.webp', 'https://villow-seeds.s3.amazonaws.com/4.webp', 'https://villow-seeds.s3.amazonaws.com/5.webp', 'https://villow-seeds.s3.amazonaws.com/6.webp', 'https://villow-seeds.s3.amazonaws.com/7.webp']::text[]),
('240 E 76th St', '240 E 76th St, New York, NY 10021', 'New York', 'NY', '10021', 'Sale', 'Co-op', '$5,506/month', 2650000, 1472, 3, 2, 1800, 1920, TRUE, TRUE, FALSE, 'Elegant three-bedroom co-op in a classic pre-war building! This spacious apartment features high ceilings, original moldings, and a wood-burning fireplace. The building offers a 24-hour doorman, a live-in superintendent, and a roof garden. Conveniently located near transportation, shops, and restaurants.', '3BR PRE-WAR CO-OP DOORMAN FIREPLACE ROOF GARDEN', 40.776157, -73.952102, ARRAY['https://villow-seeds.s3.amazonaws.com/house1.webp', 'https://villow-seeds.s3.amazonaws.com/house2.webp', 'https://villow-seeds.s3.amazonaws.com/house3.webp', 'https://villow-seeds.s3.amazonaws.com/4.webp', 'https://villow-seeds.s3.amazonaws.com/5.webp', 'https://villow-seeds.s3.amazonaws.com/6.webp', 'https://villow-seeds.s3.amazonaws.com/7.webp']::text[]),
('200 E 94th St', '200 E 94th St, New York, NY 10128', 'New York', 'NY', '10128', 'Rent', 'Condo', '$750/month', 7500, 5, 2, 2.5, 1500, 2001, TRUE, TRUE, TRUE, 'Spacious two-bedroom condo with a private balcony and city views! This modern apartment features hardwood floors, stainless steel appliances, and in-unit laundry. The building offers a 24-hour doorman, a fitness center, and a children''s playroom. Close to transportation, shops, and restaurants.', '2BR CONDO BALCONY CITY VIEWS DOORMAN FITNESS PLAYROOM', 40.776157, -73.952102, ARRAY['https://villow-seeds.s3.amazonaws.com/house1.webp', 'https://villow-seeds.s3.amazonaws.com/house2.webp', 'https://villow-seeds.s3.amazonaws.com/house3.webp', 'https://villow-seeds.s3.amazonaws.com/4.webp', 'https://villow-seeds.s3.amazonaws.com/5.webp', 'https://villow-seeds.s3.amazonaws.com/6.webp', 'https://villow-seeds.s3.amazonaws.com/7.webp']::text[]),
('120 E 87th St', '120 E 87th St, New York, NY 10128', 'New York', 'NY', '10128', 'Sale', 'Co-op', '$9,872/month', 4750000, 1583, 4, 3.5, 3000, 1929, TRUE, TRUE, FALSE, 'Stunning four-bedroom co-op with beautiful pre-war details! This grand apartment features a formal dining room, a wood-burning fireplace, and a home office. The building offers a 24-hour doorman, a live-in superintendent, and a roof terrace. Conveniently located near transportation, shops, and restaurants.', '4BR PRE-WAR CO-OP DOORMAN FIREPLACE HOME OFFICE ROOF TERRACE', 40.776157, -73.952102, ARRAY['https://villow-seeds.s3.amazonaws.com/house1.webp', 'https://villow-seeds.s3.amazonaws.com/house2.webp', 'https://villow-seeds.s3.amazonaws.com/house3.webp', 'https://villow-seeds.s3.amazonaws.com/4.webp', 'https://villow-seeds.s3.amazonaws.com/5.webp', 'https://villow-seeds.s3.amazonaws.com/6.webp', 'https://villow-seeds.s3.amazonaws.com/7.webp']::text[]),
('40 E 88th St', '40 E 88th St, New York, NY 10128', 'New York', 'NY', '10128', 'Sale', 'Condo', '$12,456/month', 5995000, 1499, 5, 5, 4000, 2020, TRUE, TRUE, TRUE, 'Exquisite five-bedroom condo with high-end finishes and top-of-the-line appliances! This stunning apartment features a large terrace, a home office, and a wine cellar. The building offers a 24-hour doorman, a fitness center, and a landscaped roof deck. Located in a prime Upper East Side location close to Central Park, museums, and restaurants.', '5BR CONDO TERRACE HOME OFFICE WINE CELLAR DOORMAN FITNESS ROOF DECK', 40.776157, -73.952102, ARRAY['https://villow-seeds.s3.amazonaws.com/house1.webp', 'https://villow-seeds.s3.amazonaws.com/house2.webp', 'https://villow-seeds.s3.amazonaws.com/house3.webp', 'https://villow-seeds.s3.amazonaws.com/4.webp', 'https://villow-seeds.s3.amazonaws.com/5.webp', 'https://villow-seeds.s3.amazonaws.com/6.webp', 'https://villow-seeds.s3.amazonaws.com/7.webp']::text[]),
('308 E 79th St', '308 E 79th St, New York, NY 10075', 'New York', 'NY', '10075', 'Rent', 'Apartment', '$315/month', 3150, 4, 1, 1, 750, 1970, TRUE, TRUE, FALSE, 'Charming one-bedroom apartment in a well-maintained building! This bright apartment features hardwood floors, a separate kitchen, and ample closet space. The building offers laundry facilities and a live-in super. Conveniently located near transportation, shops, and restaurants.', '1BR HARDWOOD FLOORS SEPARATE KITCHEN LAUNDRY', 40.776157, -73.952102, ARRAY['https://villow-seeds.s3.amazonaws.com/house1.webp', 'https://villow-seeds.s3.amazonaws.com/house2.webp', 'https://villow-seeds.s3.amazonaws.com/house3.webp', 'https://villow-seeds.s3.amazonaws.com/4.webp', 'https://villow-seeds.s3.amazonaws.com/5.webp', 'https://villow-seeds.s3.amazonaws.com/6.webp', 'https://villow-seeds.s3.amazonaws.com/7.webp']::text[]),
('100 Willow St', '100 Willow St, Brooklyn, NY 11201', 'Brooklyn', 'NY', '11201', 'Sale', 'Condo', '$6,375/month', 1275000, 911, 2, 2, 1400, 2015, TRUE, TRUE, TRUE, 'Bright Brooklyn Heights condo with an open living area, wide-plank floors, and a chef-ready kitchen. The full-service building includes a fitness room, package service, and a landscaped roof deck, all close to the promenade and neighborhood cafes.', '2BR CONDO BROOKLYN HEIGHTS ROOF DECK FITNESS', 40.6962, -73.9957, ARRAY['https://villow-seeds.s3.amazonaws.com/house1.webp']::text[]),
('30-12 30th Ave', '30-12 30th Ave, Astoria, NY 11102', 'Astoria', 'NY', '11102', 'Rent', 'Apartment', '$4,200/month', 4200, 4, 2, 1, 1050, 2008, TRUE, TRUE, FALSE, 'Sunny Astoria two-bedroom with a comfortable open layout, updated kitchen, and in-unit laundry. Steps from neighborhood dining and a short walk to the subway, with generous closets and room to work from home.', '2BR ASTORIA APARTMENT UPDATED KITCHEN LAUNDRY', 40.7661, -73.9212, ARRAY['https://villow-seeds.s3.amazonaws.com/house2.webp']::text[])
), inserted as (
  insert into public.listings (
    owner_id, title, address, city, state, zipcode, listing_type, building_type,
    est_payment, price, price_sqft, bedroom, bathroom, sqft, built_in,
    heating, ac, garage, overview, key_words, lat, lng
  )
  select
    null, r.title, r.address, r.city, r.state, r.zipcode, r.listing_type,
    r.building_type, r.est_payment, r.price, r.price_sqft, r.bedroom,
    r.bathroom, r.sqft, r.built_in, r.heating, r.ac, r.garage, r.overview,
    r.key_words, r.lat, r.lng
  from seed_rows r
  where not exists (
    select 1 from public.listings existing
    where existing.address = r.address and existing.city = r.city
  )
  returning id, address, city
)
insert into public.listing_photos (listing_id, image_url, is_primary)
select inserted.id, photo.image_url, photo.position = 1
from inserted
join seed_rows using (address, city)
cross join lateral unnest(seed_rows.photo_urls) with ordinality as photo(image_url, position);
