create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  full_name text,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  owner_id uuid references public.profiles(id) on delete set null,
  title text not null default '',
  address text not null,
  city text not null,
  state text not null,
  zipcode text not null default '',
  listing_type text not null check (listing_type in ('Sale', 'Rent')),
  building_type text not null default 'Other',
  est_payment text not null default '',
  price integer not null check (price >= 0),
  price_sqft numeric not null default 0,
  bedroom integer not null default 0 check (bedroom >= 0),
  bathroom numeric not null default 0 check (bathroom >= 0),
  sqft integer not null default 0 check (sqft >= 0),
  built_in integer,
  heating boolean not null default false,
  ac boolean not null default false,
  garage boolean not null default false,
  overview text not null default '',
  key_words text not null default '',
  status text not null default 'active' check (status in ('active', 'draft', 'sold', 'rented')),
  lat double precision,
  lng double precision,
  views integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.favorites (
  user_id uuid not null references public.profiles(id) on delete cascade,
  listing_id bigint not null references public.listings(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, listing_id)
);

create table if not exists public.listing_photos (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings(id) on delete cascade,
  image_url text not null,
  file_id text,
  is_primary boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists listings_city_state_idx on public.listings (city, state);
create index if not exists listings_price_idx on public.listings (price);
create index if not exists listings_type_idx on public.listings (listing_type);
create index if not exists listings_owner_idx on public.listings (owner_id);
create index if not exists listing_photos_listing_idx on public.listing_photos (listing_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data ->> 'full_name')
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists listings_set_updated_at on public.listings;
create trigger listings_set_updated_at
before update on public.listings
for each row execute procedure public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.listings enable row level security;
alter table public.favorites enable row level security;
alter table public.listing_photos enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile" on public.profiles
for select to authenticated using (auth.uid() = id);
drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles
for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "Public can read active listings" on public.listings;
create policy "Public can read active listings" on public.listings
for select to anon, authenticated using (status = 'active' or owner_id = auth.uid());
drop policy if exists "Owners can create listings" on public.listings;
create policy "Owners can create listings" on public.listings
for insert to authenticated with check (owner_id = auth.uid());
drop policy if exists "Owners can update listings" on public.listings;
create policy "Owners can update listings" on public.listings
for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
drop policy if exists "Owners can delete listings" on public.listings;
create policy "Owners can delete listings" on public.listings
for delete to authenticated using (owner_id = auth.uid());

drop policy if exists "Users can read own favorites" on public.favorites;
create policy "Users can read own favorites" on public.favorites
for select to authenticated using (auth.uid() = user_id);
drop policy if exists "Users can add own favorites" on public.favorites;
create policy "Users can add own favorites" on public.favorites
for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "Users can remove own favorites" on public.favorites;
create policy "Users can remove own favorites" on public.favorites
for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "Public can read listing photos" on public.listing_photos;
create policy "Public can read listing photos" on public.listing_photos
for select to anon, authenticated using (
  exists (select 1 from public.listings l where l.id = listing_id and (l.status = 'active' or l.owner_id = auth.uid()))
);
drop policy if exists "Owners can add listing photos" on public.listing_photos;
create policy "Owners can add listing photos" on public.listing_photos
for insert to authenticated with check (
  exists (select 1 from public.listings l where l.id = listing_id and l.owner_id = auth.uid())
);
drop policy if exists "Owners can delete listing photos" on public.listing_photos;
create policy "Owners can delete listing photos" on public.listing_photos
for delete to authenticated using (
  exists (select 1 from public.listings l where l.id = listing_id and l.owner_id = auth.uid())
);
